
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0

name: Release

jobs:
  crate_publish:
    name: Publish on crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install required packages
        run: sudo apt-get install -y libdbus-1-dev pkg-config

      - name: Run cargo login
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505
        with:
          command: login
          args: "${{secrets.CARGO_TOKEN}}"
 
      - name: Run cargo publish
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505
        with:
          command: publish
